### ISSUE TITLE
REST (Angular): "msw" is included in the production bundle

### ISSUE THREAD

**Issue by anymaniax** [mswjs/examples#31]
### Expected behaviour

MSW must not be included in the production bundle.

### My solution

I use the environment file to add a module in development who load my MSW config.
You have an example [here](https://github.com/anymaniax/orval/tree/master/samples/angular-app)

**Comment by kettanaito** [comment]
Hey, @anymaniax. Thanks for reaching out.

I don't have experience with Angular and its build configuration, so sorry if I may say stupid things.

From what I can see, your `main.ts` establishes the following modules dependency tree:

```
- main.ts
  - ./environments/environment
    - ../api/mocks/mock.module
      - ./mock.service
        - msw
```

Make sure you are _importing_ `msw` conditionally. It matters not if you decide to call some of its methods conditionally, the import itself must be conditional, otherwise `msw` package ends up in your build bundle. Judging by the dependency tree above, I don't see that either of those chains would been imported conditionally. Instead, I think, you rely on the build process to enable the mocks depending on environment. That leaves `msw` imported all the time, and it ends up in your build.

Take a look how the Angular example is constructed:

https://github.com/mswjs/examples/blob/master/examples/rest-angular/src/main.ts#L7-L12

The entire `./mocks/browser.js` module is required in an `if` statement, depending on the `environment.production` variable. If the `else` branch never executes, it gets stripped off by bundlers, so the `msw` is never imported anywhere.

Hope this helps. Let me know if you have any questions.

**Comment by anymaniax** [comment]
The condition doesn't work correctly. If you build the angular app without the "else" you will see that your bundle is smaller.

I followed this [example](https://dev.to/negue/performance-tree-shake-with-environment-ts-ck3) to solve the problem on my project.

**Comment by timdeschryver** [comment]
🤯 sometimes the solution can be so simple, thanks @anymaniax.

See #35 for the updated example.
