### ISSUE TITLE
Improve Storybook example

### ISSUE THREAD

**Issue by kettanaito** [mswjs/examples#39]
- Originates from https://github.com/storybookjs/storybook/issues/11378
- Concerns https://storybook.js.org/docs/react/workflows/build-pages-with-storybook

**Comment by DamianPereira** [comment]
I tried using the example code to serve an image from a public folder in storybook, using ctx.fetch and ctx.body. I had a problem where msw wasn't starting fast enough for the first requests, or something failed, because first request failed with a 404.

I managed to make it work with the following code (using loaders available in storybook 6.1):

```javascript
// preview.js

const isRunningInBrowser = () => typeof global.process === 'undefined';
let workerRun = false;

export const loaders = [
  async () => {
    // Storybook executes this module in both bootstap phase (Node)
    // and a story's runtime (browser). However, cannot call `setupWorker`
    // in Node environment, so need to check if we're in a browser.

    if (isRunningInBrowser()) {
      const { worker } = require('../fakeBackend/worker');
      // Start the mocking when each story is loaded.
      // Repetitive calls to the `.start()` method do not register a new worker,
      // but check whether there's an existing once, reusing it, if so.
      if (!workerRun && worker) {
        workerRun = true;
        await worker.start();
      }
    }
  },
];
```
If you think this is the right way maybe I can make a PR to update the example.

**Comment by kettanaito** [comment]
I'm planning to rewrite the Storybook example in the nearest future. It will use decorators instead to make the mocking much easier to set up.

**Comment by kettanaito** [comment]
The storybook example has been updated with #48.
