### ISSUE TITLE
Testing the correct data is passed to fetch

### ISSUE THREAD

**Issue by jmcrthrs** [mswjs/examples#41]
Perhaps this is the incorrect place, but I was wondering if unit testing that the correct data is passed to the endpoint is in scope when using msw.

I will use the example given here:

https://github.com/mswjs/examples/blob/0d2f30604cc8fb64ec6db277d5db627602e2a2c9/examples/rest-react/src/LoginForm.js#L25

I would like to ensure that the arguments passed to fetch are correct. e.g. the first argument is '/login', the method is 'POST' etc.

I think this is a good idea to prevent regressions, however perhaps it is out of scope for the integration test linked above.

I am interested if anyone has an idea of how I would write my unit test when using msw.

**Comment by kettanaito** [comment]
Hey, @jmcrthrs. That's alright to raise a question here, no worries.

This validation already happens when you declare [request handlers](https://mswjs.io/docs/basics/request-handler) for your API call. You provide a REST API method and a URL to a request handler, so if either of those is invalid, your API call won't get mocked and you'll see that in tests.

```js
// This, of course, won't match "POST /login"
rest.get('/user')
```

To get even more assurance calls like these are reported during test run, consider using [`onUnhandledRequest`](https://mswjs.io/docs/api/setup-server/listen#onunhandledrequest) option:

```js
server.listen({
  // Throw an exception whenever your test makes an HTTP request
  // that does not have a corresponding request handler (mock).
  onUnhandledRequest: 'error'
})
```

When it comes to asserting other request data, such as headers or body, take a read about [Request assertions](https://mswjs.io/docs/recipes/request-assertions) that goes in detail how to do (or not to do) that. Hope this helps.

**Comment by jmcrthrs** [comment]
@kettanaito Ah yes that is clear. Thanks for the response!
