### ISSUE TITLE
Change intercepted payload in a single test at runtime

### ISSUE THREAD

**Issue by artivilla** [mswjs/examples#68]
The issues filed here have been tremendously helpful so posting my ask here as it can help others as well. I'm trying to test for a deletion of a token from our UI dashboard. Posting a snippet but wanted to know if you can change your payload at runtime?

```
it('token should be deleted, () => {
      const tokenName = 'Toast';
      //...
      // define payloadBeforeDelete and payloadAfterDelete
      server.use(
            rest.get(tokenServerUrl('/tokens'), (req, res, { json }) => {
                return res(json(payloadBeforeDelete));
            }),
        );
        render(<MockAPITokenManagementWrapper />);
        await waitFor(() => expect(screen.getByTestId(`token-card-${tokenName}`)).toBeVisible());

        userEvent.click(screen.getByTestId(`token-card-${tokennGuid}-revoke-button`));
        userEvent.type(screen.getByTestId('revoke-token-dialog-token-input'), correct2FA);

        server.use(
            rest.get(tokenServerUrl('/tokens'), (req, res, { json }) => {
                return res(json(payloadAfterDelete));
            }),
        );
        userEvent.click(screen.getByRole('button', { name: /Revoke Access/i }));
        await waitFor(() => expect(screen.queryByText('Invalid code.')).not.toBeInTheDocument()); <-- this token exists
        await waitFor(() => expect(screen.queryByTestId(`token-card-${tokenName}`)).not.toBeInTheDocument());
})
```
`token-card-Toast` is still in the document so I'm unclear if you can actually call rest.get() twice in a single test.

**Comment by kettanaito** [comment]
Hey, @artivilla. Thanks for posting here for posterity.

> Posting a snippet but wanted to know if you can change your payload at runtime?

You're approaching the task correctly: use `server.use()` to prepend request handlers on runtime. Once `server.use()` is called, any new handlers are immediately added and take effect. 

If you're still experiencing a failing assertion that looks like the wrong response is being received by your app, consider one of these points:

1. Make sure that your request client does not use caching during tests. We write more about this [here](https://mswjs.io/docs/faq#why-do-i-get-stale-responses-when-using-react-queryswretc). This isn't the case for `window.fetch` but more advanced clients like React Query/Apollo/SWR/etc. introduce caching by default. **You must disable that caching during your test runs to prevent false negatives due to stale responses**.
2. Take an extra look at your assertions and make sure they are correct. Often people forget to await asynchronous things or use the wrong RTL methods for the job. This is a common case for similar issues so I feel it's worth bringing it up. 
3. Lastly, look if there are any app issues. Perhaps the correct response is not handled in the UI as you think? You can do this by either inspecting the rendered HTML via `screen.debug()` or by running your app in the browser and using `setupWorker` to see how the UI behaves.
